version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./docs:/app/docs
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./app.db}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here-change-in-production}
      - LD_LIBRARY_PATH=
    command: python main.py
    restart: unless-stopped

  celery:
    build: .
    volumes:
      - .:/app
      - ./docs:/app/docs
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./app.db}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here-change-in-production}
      - LD_LIBRARY_PATH=
    command: celery -A celery_app worker --loglevel=info --concurrency=4
    restart: unless-stopped

  flower:
    build: .
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - LD_LIBRARY_PATH=
    command: celery -A celery_app flower --port=5555
    restart: unless-stopped

volumes:
  redis_data: